[build]
  base    = "frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL         = "https://wr-energy-production.up.railway.app"
  VITE_WHATSAPP_NUMBER = "525575155669"
